### ISSUE TITLE
Extra output: one `C` for each model run

### ISSUE THREAD

**Issue by Yodo9000** [attogram/ollama-multirun#14]
Whenever I run `multirun.sh` using Cygwin on Windows 10, the command prompt comes back as `$ CCC` with one `C` for each model that it has run.

Steps to reproduce:

0. Run via Cygwin on Windows 10
1. Run `./multirun.sh ""` (for example)

What happens:
The models run as normally, but the command prompt comes back as `$ CCC` with one `C` for each model that it has run (3 in my example).

What I expected:
The command prompt comes back empty: `$ `

I'm not sure if this is an issue with `multirun.sh`, or becuase of how I'm running it. I do get the error message `top: unknown option -- l` while running it, but it seems to work fine otherwise. I get the extra `C`s in interactive and in-line mode.

**Comment by attogram** [comment]
v5.2 update should fix these issues.    Still todo: get actual memory stats from cygwin, instead of just showing '`?`'

**Comment by Yodo9000** [comment]
In version 5.3 it is not fixed. `top: unknown option -- l` does not appear anymore though. Should I open a new issue?

**Comment by Yodo9000** [comment]
To run `multirun.sh` on windows I also need to use `dos2unix` in Cygwin to change the encoding. I think this is because the encoding of some characters changes during downloading due to it technically being stored on a Windows filesystem.

**Comment by Yodo9000** [comment]
Thanks! It works as expected now.
